### ISSUE TITLE
failover:(tcp://localhost:61616,tcp://remotehost:61616)?

### ISSUE THREAD

**Issue by hafezieh** [tomitribe/JMS-1.1-PubSub-Queue-Example-with-ActiveMQ#1]
how can i configure this project with failover:(tcp://localhost:61616,tcp://remotehost:61616)? to implement clustering for 2 brokers for example ?

**Comment by hafezieh** [comment]
how can i configure this project with failover:(tcp://localhost:61616,tcp://remotehost:61616)? to implement clustering for 2 brokers for example ?

**Comment by cesarhernandezgt** [comment]
Hi @hafezieh,

Failover falls outside of the scope of the blog post "[5 Minutes or Less: ActiveMQ with JMS Queues and Topics](https://www.tomitribe.com/blog/5-minutes-or-less-activemq-with-jms-queues-and-topics/)" that gave origin to this repository.

For failover configuration, check out the following resources:

https://activemq.apache.org/how-do-i-configure-automatic-reconnection
https://activemq.apache.org/failover-transport-reference.html

**Comment by hafezieh** [comment]
Hi @cesarhernandezgt 

Thanks a lot, I actually did it with some changes in the Consumer.java and Producer.java to perform a mini failover with two broker
in JmsConnectionFactory i wrote : new JmsConnectionFactory(failover:(amqp://myBrokerHost1:5672,amqp://myBrokerHost2:5672)?initialReconnectDelay=100");
and that seems OK!
when myBroker in Host1 stop, myBroker in Host2 send messages to my Consumers and vice versa
